name: banhang
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.2
  flutter_html: ^3.0.0-alpha.5 #prd-detail
  flutter_svg: ^1.1.6

  font_awesome_flutter: ^10.5.0
  line_awesome_flutter: ^1.0.0
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  flutter_snake_navigationbar: ^0.6.1
  badges: ^3.1.2
  shimmer: ^3.0.0
  carousel_slider: ^5.0.0
  scoped_model: ^2.0.0
  cached_network_image: ^3.2.0
  intl: ^0.18.1

  hive_flutter: ^1.0.8
  email_validator: ^2.0.1 #regis-screen

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/
